"""
Setup script for multi-environment training.

Creates N game instance directories using symlinks to save disk space.
Each instance gets its own BepInEx folder with a unique dote_training.cfg
specifying different IPC ports.

Usage:
    python scripts/setup_multi_env.py --num-envs 3
    python scripts/setup_multi_env.py --num-envs 4 --source "D:\Games\DotE" --dest "C:\DotE_Training"

Requirements:
    - Must run as Administrator (for symlink creation on Windows)
    - Source game directory must have BepInEx installed with the mod DLL

What it creates:
    dest/
    ├── instance_0/          (symlinks to source, own BepInEx with port 5555/5556)
    ├── instance_1/          (symlinks to source, own BepInEx with port 5557/5558)
    ├── instance_2/          (symlinks to source, own BepInEx with port 5559/5560)
    └── launch_all.ps1       (script to launch all instances)
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

DEFAULT_SOURCE = r"C:\Program Files (x86)\Steam\steamapps\common\Dungeon of the Endless"
DEFAULT_DEST = r"C:\DotE_Training"
BASE_STATE_PORT = 5555
BASE_ACTION_PORT = 5556

# Files/folders in the game root that we symlink (read-only game data)
# Everything else gets copied or created fresh
SYMLINK_ITEMS = [
    "DungeonoftheEndless.exe",
    "DungeonoftheEndless_Data",
    "Mono",
    "Managed",  # May not exist separately (sometimes inside _Data)
    "Resources",
    "Plugins",
    # Common Unity game files
    "UnityEngine.dll",
    "Assembly-CSharp.dll",
    "Assembly-CSharp-firstpass.dll",
    "Assembly-UnityScript-firstpass.dll",
    "Assembly-UnityScript.dll",
]


def create_instance(
    source: Path,
    dest: Path,
    instance_index: int,
    state_port: int,
    action_port: int,
    time_scale: int = 8,
) -> Path:
    """
    Create a single game instance directory.

    Strategy:
    - Create the instance directory
    - Symlink (junction for dirs, hardlink/symlink for files) everything from source
      EXCEPT BepInEx (which we copy and customize)
    - Copy BepInEx folder entirely (it's small, ~5MB)
    - Write a custom dote_training.cfg with the unique ports
    """
    instance_dir = dest / f"instance_{instance_index}"

    if instance_dir.exists():
        print(f"  Instance {instance_index} already exists, skipping...")
        return instance_dir

    instance_dir.mkdir(parents=True)
    print(f"  Creating instance_{instance_index} (ports {state_port}/{action_port})...")

    # Iterate over everything in source
    for item in source.iterdir():
        target = instance_dir / item.name

        if item.name == "BepInEx":
            # Copy BepInEx entirely (we need to modify the config)
            shutil.copytree(item, target)
        elif item.name.endswith("_Data"):
            # Full copy of Data folder — Unity locks files here, junctions won't work
            print(f"    Copying {item.name} ({_dir_size_mb(item):.0f} MB)...")
            shutil.copytree(item, target)
        elif item.is_dir():
            # Create directory junction (Windows symlink for dirs)
            _create_junction(target, item)
        else:
            # Create file symlink (or hardlink)
            try:
                os.link(str(item), str(target))  # Hardlink (same volume)
            except OSError:
                try:
                    os.symlink(str(item), str(target))  # Symlink (cross-volume)
                except OSError:
                    # Fall back to copy for small files
                    shutil.copy2(item, target)

    # Write custom dote_training.cfg
    cfg_path = instance_dir / "BepInEx" / "plugins" / "dote_training.cfg"
    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    cfg_content = (
        f"# DotE Agent Training Config - Instance {instance_index}\n"
        f"# Auto-generated by setup_multi_env.py\n"
        f"\n"
        f"training_mode=true\n"
        f"time_scale={time_scale}\n"
        f"resolution_width=640\n"
        f"resolution_height=480\n"
        f"state_port={state_port}\n"
        f"action_port={action_port}\n"
    )
    cfg_path.write_text(cfg_content)

    print(f"    Config: state_port={state_port}, action_port={action_port}")
    return instance_dir


def _create_junction(link_path: Path, target_path: Path) -> None:
    """Create a Windows directory junction (doesn't require admin like symlinks)."""
    # mklink /J doesn't require elevated privileges on Windows
    cmd = f'mklink /J "{link_path}" "{target_path}"'
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if result.returncode != 0:
        # Fallback: try regular symlink (needs admin)
        try:
            os.symlink(str(target_path), str(link_path), target_is_directory=True)
        except OSError as e:
            print(f"    WARNING: Could not create junction for {link_path.name}: {e}")
            print(f"    Falling back to full copy...")
            shutil.copytree(target_path, link_path)


def _dir_size_mb(path: Path) -> float:
    """Get total size of a directory in MB."""
    total = 0
    for f in path.rglob("*"):
        if f.is_file():
            total += f.stat().st_size
    return total / (1024 * 1024)


def create_launch_script(dest: Path, num_envs: int) -> None:
    """Create a PowerShell script that launches all game instances."""
    script_path = dest / "launch_all.ps1"
    lines = [
        "# Launch all DotE training instances",
        f"# Auto-generated for {num_envs} instances",
        "",
    ]
    for i in range(num_envs):
        instance_dir = dest / f"instance_{i}"
        exe_path = instance_dir / "DungeonoftheEndless.exe"
        lines.append(f'Write-Host "Launching instance {i}..."')
        lines.append(f'Start-Process -FilePath "{exe_path}" -WorkingDirectory "{instance_dir}"')
        lines.append("Start-Sleep -Seconds 5")
        lines.append("")

    lines.append(f'Write-Host "All {num_envs} instances launched."')
    lines.append('Write-Host "Wait for all to reach main menu, then run:"')
    lines.append(f'Write-Host "  python src/agent/train_multi_env.py --num-envs {num_envs} --no-launch"')

    script_path.write_text("\n".join(lines))
    print(f"\nLaunch script: {script_path}")


def main():
    parser = argparse.ArgumentParser(description="Setup multi-env game instances for RL training")
    parser.add_argument("--num-envs", type=int, default=3, help="Number of instances to create")
    parser.add_argument("--source", type=str, default=DEFAULT_SOURCE, help="Source game directory")
    parser.add_argument("--dest", type=str, default=DEFAULT_DEST, help="Destination for instances")
    parser.add_argument("--time-scale", type=int, default=8, help="Game speed for all instances")
    args = parser.parse_args()

    source = Path(args.source)
    dest = Path(args.dest)

    if not source.exists():
        print(f"ERROR: Source directory not found: {source}")
        sys.exit(1)

    exe = source / "DungeonoftheEndless.exe"
    if not exe.exists():
        print(f"ERROR: Game exe not found: {exe}")
        sys.exit(1)

    bepinex = source / "BepInEx"
    if not bepinex.exists():
        print(f"ERROR: BepInEx not found in source. Install BepInEx + mod first.")
        sys.exit(1)

    print(f"Source: {source}")
    print(f"Destination: {dest}")
    print(f"Instances: {args.num_envs}")
    print(f"Time scale: {args.time_scale}x")
    print()

    dest.mkdir(parents=True, exist_ok=True)

    instance_dirs = []
    for i in range(args.num_envs):
        state_port = BASE_STATE_PORT + (i * 2)
        action_port = BASE_ACTION_PORT + (i * 2)
        instance_dir = create_instance(
            source, dest, i, state_port, action_port, args.time_scale
        )
        instance_dirs.append(instance_dir)

    create_launch_script(dest, args.num_envs)

    print()
    print("=" * 60)
    print("SETUP COMPLETE")
    print("=" * 60)
    print()
    print("Next steps:")
    print(f"  1. Run: powershell {dest / 'launch_all.ps1'}")
    print(f"  2. Wait for all instances to reach the main menu")
    print(f"  3. Run: python src/agent/train_multi_env.py --num-envs {args.num_envs} --no-launch")
    print()
    print("Port assignments:")
    for i in range(args.num_envs):
        sp = BASE_STATE_PORT + (i * 2)
        ap = BASE_ACTION_PORT + (i * 2)
        print(f"  Instance {i}: state={sp}, action={ap}")


if __name__ == "__main__":
    main()
